# -*- coding: utf-8 -*-
"""FAKE Currency Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdzFHVrRh_-5dSQBcMYOwOghqZguC3S1
"""

# 1. Upload your test image
from google.colab import files
uploaded = files.upload()

# 2. Load and preprocess the image
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.feature import local_binary_pattern
import joblib

# Grab the uploaded filename
filename = next(iter(uploaded))

# Preprocess
def preprocess_image(image_path):
    img = cv2.imread(image_path)
    img = cv2.resize(img, (1200, 512))
    img = cv2.fastNlMeansDenoisingColored(img, None, 10, 10, 7, 21)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    v = np.median(img)
    sigma = 0.33
    lower = int(max(0, (1.0 - sigma) * v))
    upper = int(min(255, (1.0 + sigma) * v))
    img = cv2.Canny(img, lower, upper)
    return img

img = preprocess_image(filename)

# Show processed image
plt.imshow(img, cmap='gray')
plt.title("Preprocessed Image")
plt.axis('off')
plt.show()

# Feature extraction coordinates (can be tuned)
coords = [
    (195, 170, 190, 85),
    (330, 105, 720, 105),
    (320, 90, 865, 205),
    (250, 40, 1120, 40),
    (5, 405, 660, 40),
    (284, 132, 1090, 90),
]

def extract_features(img, coords):
    features = []
    for (y, h, x, w) in coords:
        feature = img[y:y+h, x:x+w]
        features.append(feature)
    return features

features = extract_features(img, coords)

def compute_lbp_histograms(features):
    radius = 3
    n_points = 8 * radius
    histograms = []
    for feature in features:
        lbp = local_binary_pattern(feature, n_points, radius, method='uniform')
        n_bins = int(lbp.max() + 1)
        hist, _ = np.histogram(lbp, density=True, bins=n_bins, range=(0, n_bins))
        histograms.append(hist)
    return histograms

histograms = compute_lbp_histograms(features)

# 3. Upload and load pre-trained histograms (lbp.pkl)
print("Upload the lbp.pkl file now")
files.upload()
X_test500, X_test2000, _ = joblib.load("lbp.pkl")

thresholds = [0.006, 0.02, 0.008, 0.06, 0.02, 0.07]

def classify(histograms, reference_data, thresholds):
    total_score = 0
    for i, hist in enumerate(histograms):
        ref_hists = reference_data[i]
        score = np.mean([
            cv2.compareHist(np.array(ref, dtype=np.float32),
                            np.array(hist, dtype=np.float32),
                            cv2.HISTCMP_CHISQR)
            for ref in ref_hists
        ])
        if score > thresholds[i]:
            return False
        total_score += score
    return True

# 4. Classification
is_500_genuine = classify(histograms, X_test500, thresholds)
is_2000_genuine = classify(histograms, X_test2000, thresholds)

if is_500_genuine and not is_2000_genuine:
    print("✅ Detected: ₹500 Currency Note - GENUINE")
elif is_2000_genuine and not is_500_genuine:
    print("✅ Detected: ₹2000 Currency Note - GENUINE")
else:
    print("❌ Detected: FAKE Currency Note")

